# Scikit-learn preprocessing

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = np.random.randint(0, 100, (10, 2))

In [3]:
data

array([[16,  3],
       [45, 43],
       [49, 89],
       [52, 35],
       [25, 92],
       [42, 35],
       [13, 21],
       [67, 22],
       [88, 61],
       [30, 52]])

In [4]:
scaler_model = MinMaxScaler()
scaler_model.fit(data)

/home/yilingchen/miniconda3/envs/udacity/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [5]:
# NOTE: scaling occurs in each column
scaler_model.transform(data)

array([[ 0.04      ,  0.        ],
       [ 0.42666667,  0.4494382 ],
       [ 0.48      ,  0.96629213],
       [ 0.52      ,  0.35955056],
       [ 0.16      ,  1.        ],
       [ 0.38666667,  0.35955056],
       [ 0.        ,  0.20224719],
       [ 0.72      ,  0.21348315],
       [ 1.        ,  0.65168539],
       [ 0.22666667,  0.5505618 ]])

In [6]:
scaler_model.fit_transform(data)

/home/yilingchen/miniconda3/envs/udacity/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)

array([[ 0.04      ,  0.        ],
       [ 0.42666667,  0.4494382 ],
       [ 0.48      ,  0.96629213],
       [ 0.52      ,  0.35955056],
       [ 0.16      ,  1.        ],
       [ 0.38666667,  0.35955056],
       [ 0.        ,  0.20224719],
       [ 0.72      ,  0.21348315],
       [ 1.        ,  0.65168539],
       [ 0.22666667,  0.5505618 ]])

## Train-Test Split

In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame(data=np.random.randint(0, 101, (50, 4)), columns=['f1', 'f2', 'f3', 'label'])

In [9]:
df

     f1  f2  f3  label
0   100  47   3     12
1    85   5  55     29
2    52  73  90     51
3    61  96  76      8
4    17  20  96     36
5    25  34  23      6
6    91  70   4     87
7    48  99  56     82
8    66  97  68     30
9    17  25  69     34
10   44  50  92    100
11   81  83  76     24
12   51  21   1     19
13   67  97  87     98
14   21  90  89     27
15   27   6  11    100
16   10  91  13     48
17    1  43  42     33
18  100  67  29     23
19   75  25  34     20
20   94  61  70     18
21   23  98  87     98
22   69  85  92      0
23   53  59  53     19
24   99   0  20     11
25   30  76   5     97
26   74  11  29     93
27   14  88  85     13
28    7  97  58     25
29   14  41  78     31
30   40  76  35     15
31    0  60  51     69
32   82  57  69     34
33   48  11  77     90
34   46  16  38     61
35   28  17  88     42
36    2  75  90     53
37   68  77  34     45
38   13  57  86     65
39   46  38  77     55
40   49  21  47     24
41    5  60  45     67
42   99   3   1     41
43   66  30  56     13
44   89  89  26     83
45   58   1  93     74
46   28   9  31     51
47   12  36  20     37
48   24  69  84     91
49   58  74  78     33

In [10]:
X = df[['f1', 'f2', 'f3']]
y = df['label']

In [11]:
y

0      12
1      29
2      51
3       8
4      36
5       6
6      87
7      82
8      30
9      34
10    100
11     24
12     19
13     98
14     27
15    100
16     48
17     33
18     23
19     20
20     18
21     98
22      0
23     19
24     11
25     97
26     93
27     13
28     25
29     31
30     15
31     69
32     34
33     90
34     61
35     42
36     53
37     45
38     65
39     55
40     24
41     67
42     41
43     13
44     83
45     74
46     51
47     37
48     91
49     33
Name: label, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [14]:
X_train.shape

(35, 3)

In [15]:
X_test.shape

(15, 3)